/**
 * App Redux Action Types
 */

// Auth Actions
export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const LOGOUT_USER = 'LOGOUT_USER'
export const SIGNUP_USER = 'SIGNUP_USER'
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS'
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE'
export const LOGIN_FACEBOOK_USER = 'LOGIN_FACEBOOK_USER'
export const LOGIN_GOOGLE_USER = 'LOGIN_GOOGLE_USER'
export const LOGIN_TWITTER_USER = 'LOGIN_TWITTER_USER'
export const LOGIN_GITHUB_USER = 'LOGIN_GITHUB_USER'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE'

// Form Actions
export const UPDATE_FIELD = 'UPDATE_FIELD'
export const UPDATE_FIELD_ARRAY = 'UPDATE_FIELD_ARRAY'
export const UPDATE_ERRORS = 'UPDATE_ERRORS'
export const PUSH_FIELD_ARRAY = 'PUSH_FIELD_ARRAY'
export const UPDATE_FORM_ID = 'SET_FORM_ID'

export const UPDATE_VALID_FORM = 'SET_VALID_FORM'
export const RESET_ALL = 'RESET_ALL'

export const LOAD_INFO = 'LOAD_INFO'
export const UNLOAD_ALL = 'UNLOAD_ALL'
export const UNLOAD_ONE = 'UNLOAD_ONE'
