version: '2'
services:

  web:
    build: .
    env_file: .env
    working_dir: /ht
    volumes:
      - "./:/ht"
    command: bash -c 'bundle exec whenever --update-crontab & bin/webpack --watch --progress --color & bin/rails s -p 3000 -b "0.0.0.0"'
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - sidekiq
      - selenium
      - elasticsearch
      - elasticsearch_test

    links:
      - postgres:postgres
      - selenium:selenium
    environment:
      - ELASTICSEARCH_URL=elasticsearch
      - ELASTICSEARCH_TEST_URL=elasticsearch_test

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
    shm_size: 512M

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
      environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - xpack.security.enabled=false
        - xpack.monitoring.enabled=false
        - xpack.graph.enabled=false
        - xpack.watcher.enabled=false
        - discovery.type=single-node
      ulimits:
        nproc: 65535
        memlock:
          soft: -1
          hard: -1
      mem_limit: 1g
      volumes:
        - elasticsearch_data:/usr/share/elasticsearch/data
      ports:
        - 9200:9200

  elasticsearch_test:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
      environment:
        - cluster.name=docker-cluster_test
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - xpack.security.enabled=false
        - xpack.monitoring.enabled=false
        - xpack.graph.enabled=false
        - xpack.watcher.enabled=false
        - discovery.type=single-node
      ulimits:
        nproc: 65535
        memlock:
          soft: -1
          hard: -1
      mem_limit: 1g
      volumes:
        - elasticsearch_test_data:/usr/share/elasticsearch/data
      ports:
        - 9250:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1

  redis:
    image: 'redis:6.0-rc2-alpine'
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - 'redis_data:/data'

  sidekiq:
    tty: true
    stdin_open: true
    depends_on:
      - postgres
      - redis
    build: .
    volumes:
      - "./:/ht"
    command: bundle exec sidekiq -C config/sidekiq.yml
    env_file: .env

volumes:
  postgres_data:
    driver: local
  elasticsearch_data:
    driver: local
  elasticsearch_test_data:
    driver: local
  redis_data:
    driver: local
