version: '2'
services:
  web:
    working_dir: /ht
    build: .
    volumes:
      - "./:/ht"
    command: bash -c 'bin/webpack --watch --progress --color & bin/rails s -p 3000 -b "0.0.0.0"'
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    links:
      - postgres:postgres
  postgres:
    image: postgres
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
