default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: postgres
  password:

development:
  <<: *default
  database: ht_development

test:
  <<: *default
  database: ht_test

production:
  <<: *default
  database: ht_production
  username: ht
  password: <%= ENV['HT_DATABASE_PASSWORD'] %>
