# config/meta.yml

meta_product_name: "HoyTrabajas.com"
meta_title: "El trabajo compatible con tu perfil. Solo en HoyTrabajas.com"
meta_description: 'La conexión perfecta entre tu perfil laboral y miles de ofertas de empleo. Encuentra trabajo commpatibles a tus habilidades, competencias y experiencia.'
meta_image: "hoytrabajas-logo-color.png"
twitter_account: "@hoytrabajas"