LaborDisponibility.create!(description: 'Disponibilidad inmediata')
LaborDisponibility.create!(description: 'Disponible, pero no para iniciar inmediatamente')
LaborDisponibility.create!(description: 'No estoy disponible')
Nationality.create!(description: 'Argentina')
Nationality.create!(description: 'Bolivia')
Nationality.create!(description: 'Brasil')
Nationality.create!(description: 'Chile')
Nationality.create!(description: 'Colombia')
Nationality.create!(description: 'Costa Rica')
Nationality.create!(description: 'Cuba')
Nationality.create!(description: 'Ecuador')
Nationality.create!(description: 'El Salvador')
Nationality.create!(description: 'Guatamala')
Nationality.create!(description: 'Honduras')
Nationality.create!(description: 'México')
Nationality.create!(description: 'Nicaragua')
Nationality.create!(description: 'Panama')
Nationality.create!(description: 'Paraguay')
Nationality.create!(description: 'Puerto Rico')
Nationality.create!(description: 'Perú')
Nationality.create!(description: 'República Dominicana')
Nationality.create!(description: 'Uruguay')
Nationality.create!(description: 'Venezuela')
Nationality.create!(description: 'España')
DocumentType.create!(description: 'Cédula de ciudadanía')
DocumentType.create!(description: 'Cédula de extranger')
DocumentType.create!(description: 'Pasaporte')
JobCategory.create!(description: 'Ventas y comercial')
JobCategory.create!(description: 'Gestión administrativa')
JobCategory.create!(description: 'Operario')
JobCategory.create!(description: 'Logística y transporte')
JobCategory.create!(description: 'Belleza, bienestar y salud')
JobCategory.create!(description: 'Servicios generales y limpieza')
JobCategory.create!(description: 'Cocina, bar y meseros')
JobCategory.create!(description: 'Tecnología y programación')
JobCategory.create!(description: 'Seguridad')
JobCategory.create!(description: 'Marketing, diseño y publicidad')
JobCategory.create!(description: 'Eventos y protocolo')
JobAids.create!(description: "Auxilio de transporte")
JobAids.create!(description: "Comisiones")
Sex.create!(description: 'Masculino')
Sex.create!(description: 'Femenino')
Sex.create!(description: 'Indiferente')
Limitation.create!(description: 'Ninguna')
Limitation.create!(description: 'Física/Movilidad')
Limitation.create!(description: 'Auditiva')
Limitation.create!(description: 'Visual')
Limitation.create!(description: 'Mental')
Limitation.create!(description: 'Viseral')
EducationalDegree.create!(description: 'Primaria')
EducationalDegree.create!(description: 'Bachiller')
EducationalDegree.create!(description: 'Ténico/Tecnogo')
EducationalDegree.create!(description: 'Profesional')
EducationalDegree.create!(description: 'Especialización')
EducationalDegree.create!(description: 'Maestría')
EducationalDegree.create!(description: 'Doctorado')
OfferType.create!(description: 'Indiferente')
OfferType.create!(description: 'Trabajo tiempo completo')
OfferType.create!(description: 'Trabajo por proyecto')
OfferType.create!(description: 'Trabajo medio completo')
OfferType.create!(description: 'Trabajo por horas')
OfferType.create!(description: 'Trabajo fines de semana')
OfferType.create!(description: 'Trabajo por semana')
ContractType.create!(description: 'Prestación de servicios')
ContractType.create!(description: 'Término indefinido')
ContractType.create!(description: 'Temporal')
ContractType.create!(description: 'De aprendizaje')
ContractType.create!(description: 'Indiferente')
ContractType.create!(description: 'Por definir')
WorkMode.create!(description: 'Teletrabajo/Remoto')
WorkMode.create!(description: 'Presencial')
WorkMode.create!(description: 'Combinado')
WorkMode.create!(description: 'Indiferente')
City.create!(description: 'Bogotá')
City.create!(description: 'Cali')
City.create!(description: 'Medellín')
City.create!(description: 'Cartagena')
City.create!(description: 'Santa Marta')
City.create!(description: 'Barranquilla')
City.create!(description: 'Cota')
City.create!(description: 'Funza')
City.create!(description: 'Mosquera')
City.create!(description: 'Tocancipa')
City.create!(description: 'Sopó')
City.create!(description: 'Yopal')
City.create!(description: 'Ibague')
Vehicle.create!(description: 'Carro')
Vehicle.create!(description: 'Moto')
Vehicle.create!(description: 'Furgoneta')
Vehicle.create!(description: 'Ninguno/Indiferente')
DrivingLicence.create!(description: 'A2 (Motos)')
DrivingLicence.create!(description: 'B1 (Autos)')
DrivingLicence.create!(description: 'B2 (Caminones y buses)')
DrivingLicence.create!(description: 'Ninguno/Indiferente')
WorkingDay.create!(description: 'Mañana (7am-12pm)')
WorkingDay.create!(description: 'Tarde (12pm-5pm)')
WorkingDay.create!(description: 'Media tarde (5pm-10pm)')
WorkingDay.create!(description: 'Noche (10pm-3am)')
WorkingDay.create!(description: 'Jornada completa (8am-5pm)')
Currency.create!(description: 'COP')
Currency.create!(description: 'USD')
EmployeesRange.create!(description: '1 - 5')
EmployeesRange.create!(description: '6 - 20')
EmployeesRange.create!(description: '21 - 50')
EmployeesRange.create!(description: '> 50')
SalaryPeriod.create!(description: 'Hora')
SalaryPeriod.create!(description: 'Día')
SalaryPeriod.create!(description: 'Semana')
SalaryPeriod.create!(description: 'Quincena')
SalaryPeriod.create!(description: 'Mes')
SalaryType.create!(description: 'Fijo')
SalaryType.create!(description: 'Rango')
AvailableWorkDay.create!(description: "Lunes")
AvailableWorkDay.create!(description: "Martes")
AvailableWorkDay.create!(description: "Miércoles")
AvailableWorkDay.create!(description: "Jueves")
AvailableWorkDay.create!(description: "Viernes")
AvailableWorkDay.create!(description: "Sábado")
AvailableWorkDay.create!(description: "Lunes a viernes")
AvailableWorkDay.create!(description: "Fines de semana")
AvailableWorkDay.create!(description: "Todos los días")
