class DataForCityAndState < ActiveRecord::Migration[6.0]
  def up
    State.create(description:'Amazonas')
    State.create(description:'Antioquia')
    State.create(description:'Arauca')
    State.create(description:'Archipiélago de San Andrés, Providencia y Santa Catalina')
    State.create(description:'Atlántico')
    State.create(description:'Bogotá, D.C.')
    State.create(description:'Bolívar')
    State.create(description:'Boyacá')
    State.create(description:'Caldas')
    State.create(description:'Caquetá')
    State.create(description:'Casanare')
    State.create(description:'Cauca')
    State.create(description:'Cesar')
    State.create(description:'Chocó')
    State.create(description:'Córdoba')
    State.create(description:'Cundinamarca')
    State.create(description:'Guainía')
    State.create(description:'Guaviare')
    State.create(description:'Huila')
    State.create(description:'La Guajira')
    State.create(description:'Magdalena')
    State.create(description:'Meta')
    State.create(description:'Nariño')
    State.create(description:'Norte de Santander')
    State.create(description:'Putumayo')
    State.create(description:'Quindio')
    State.create(description:'Risaralda')
    State.create(description:'Santander')
    State.create(description:'Sucre')
    State.create(description:'Tolima')
    State.create(description:'Valle del Cauca')
    State.create(description:'Vaupés')
    State.create(description:'Vichada')

    City.create(description:'EL ENCANTO', state_id: State.find_by(description:'Amazonas').id)
City.create(description:'LA CHORRERA', state_id: State.find_by(description:'Amazonas').id)
City.create(description:'LA PEDRERA', state_id: State.find_by(description:'Amazonas').id)
City.create(description:'LA VICTORIA', state_id: State.find_by(description:'Amazonas').id)
City.create(description:'LETICIA', state_id: State.find_by(description:'Amazonas').id)
City.create(description:'MIRITI-PARANÁ', state_id: State.find_by(description:'Amazonas').id)
City.create(description:'PUERTO ALEGRÍA', state_id: State.find_by(description:'Amazonas').id)
City.create(description:'PUERTO ARICA', state_id: State.find_by(description:'Amazonas').id)
City.create(description:'PUERTO NARIÑO', state_id: State.find_by(description:'Amazonas').id)
City.create(description:'PUERTO SANTANDER', state_id: State.find_by(description:'Amazonas').id)
City.create(description:'TARAPACÁ', state_id: State.find_by(description:'Amazonas').id)
City.create(description:'ABEJORRAL', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'ABRIAQUÍ', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'ALEJANDRÍA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'AMAGÁ', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'AMALFI', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'ANDES', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'ANGELÓPOLIS', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'ANGOSTURA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'ANORÍ', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'ANZA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'APARTADÓ', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'ARBOLETES', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'ARGELIA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'ARMENIA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'BARBOSA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'BELLO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'BELMIRA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'BETANIA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'BETULIA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'BRICEÑO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'BURITICÁ', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'CÁCERES', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'CAICEDO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'CALDAS', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'CAMPAMENTO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'CAÑASGORDAS', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'CARACOLÍ', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'CARAMANTA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'CAREPA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'CAROLINA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'CAUCASIA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'CHIGORODÓ', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'CISNEROS', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'CIUDAD BOLÍVAR', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'COCORNÁ', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'CONCEPCIÓN', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'CONCORDIA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'COPACABANA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'DABEIBA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'DON MATÍAS', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'EBÉJICO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'EL BAGRE', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'EL CARMEN DE VIBORAL', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'EL SANTUARIO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'ENTRERRIOS', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'ENVIGADO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'FREDONIA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'FRONTINO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'GIRALDO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'GIRARDOTA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'GÓMEZ PLATA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'GRANADA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'GUADALUPE', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'GUARNE', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'GUATAPE', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'HELICONIA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'HISPANIA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'ITAGUI', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'ITUANGO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'JARDÍN', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'JERICÓ', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'LA CEJA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'LA ESTRELLA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'LA PINTADA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'LA UNIÓN', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'LIBORINA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'MACEO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'MARINILLA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'MONTEBELLO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'MURINDÓ', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'MUTATÁ', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'NARIÑO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'NECHÍ', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'NECOCLÍ', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'OLAYA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'PEÑOL', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'PEQUE', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'PUEBLORRICO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'PUERTO BERRÍO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'PUERTO NARE', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'PUERTO TRIUNFO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'REMEDIOS', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'RETIRO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'RIONEGRO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'SABANALARGA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'SABANETA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'SALGAR', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'SAN ANDRÉS DE CUERQUÍA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'SAN CARLOS', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'SAN FRANCISCO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'SAN JERÓNIMO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'SAN JOSÉ DE LA MONTAÑA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'SAN JUAN DE URABÁ', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'SAN LUIS', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'SAN PEDRO DE LOS MILAGROS', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'SAN PEDRO DE URABA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'SAN RAFAEL', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'SAN ROQUE', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'SAN VICENTE', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'SANTA BÁRBARA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'SANTA ROSA DE OSOS', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'SANTAFÉ DE ANTIOQUIA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'SANTO DOMINGO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'SEGOVIA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'SONSON', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'SOPETRÁN', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'TÁMESIS', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'TARAZÁ', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'TARSO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'TITIRIBÍ', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'TOLEDO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'TURBO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'URAMITA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'URRAO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'VALDIVIA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'VALPARAÍSO', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'VEGACHÍ', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'VENECIA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'VIGÍA DEL FUERTE', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'YALÍ', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'YARUMAL', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'YOLOMBÓ', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'YONDÓ', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'ZARAGOZA', state_id: State.find_by(description:'Antioquia').id)
City.create(description:'ARAUCA', state_id: State.find_by(description:'Arauca').id)
City.create(description:'ARAUQUITA', state_id: State.find_by(description:'Arauca').id)
City.create(description:'CRAVO NORTE', state_id: State.find_by(description:'Arauca').id)
City.create(description:'FORTUL', state_id: State.find_by(description:'Arauca').id)
City.create(description:'PUERTO RONDÓN', state_id: State.find_by(description:'Arauca').id)
City.create(description:'SARAVENA', state_id: State.find_by(description:'Arauca').id)
City.create(description:'TAME', state_id: State.find_by(description:'Arauca').id)
City.create(description:'PROVIDENCIA', state_id: State.find_by(description:'Archipiélago de San Andrés, Providencia y Santa Catalina').id)
City.create(description:'SAN ANDRÉS', state_id: State.find_by(description:'Archipiélago de San Andrés, Providencia y Santa Catalina').id)
City.create(description:'BARANOA', state_id: State.find_by(description:'Atlántico').id)
City.create(description:'CAMPO DE LA CRUZ', state_id: State.find_by(description:'Atlántico').id)
City.create(description:'CANDELARIA', state_id: State.find_by(description:'Atlántico').id)
City.create(description:'GALAPA', state_id: State.find_by(description:'Atlántico').id)
City.create(description:'JUAN DE ACOSTA', state_id: State.find_by(description:'Atlántico').id)
City.create(description:'LURUACO', state_id: State.find_by(description:'Atlántico').id)
City.create(description:'MALAMBO', state_id: State.find_by(description:'Atlántico').id)
City.create(description:'MANATÍ', state_id: State.find_by(description:'Atlántico').id)
City.create(description:'PALMAR DE VARELA', state_id: State.find_by(description:'Atlántico').id)
City.create(description:'PIOJÓ', state_id: State.find_by(description:'Atlántico').id)
City.create(description:'POLONUEVO', state_id: State.find_by(description:'Atlántico').id)
City.create(description:'PONEDERA', state_id: State.find_by(description:'Atlántico').id)
City.create(description:'PUERTO COLOMBIA', state_id: State.find_by(description:'Atlántico').id)
City.create(description:'REPELÓN', state_id: State.find_by(description:'Atlántico').id)
City.create(description:'SABANAGRANDE', state_id: State.find_by(description:'Atlántico').id)
City.create(description:'SABANALARGA', state_id: State.find_by(description:'Atlántico').id)
City.create(description:'SANTA LUCÍA', state_id: State.find_by(description:'Atlántico').id)
City.create(description:'SANTO TOMÁS', state_id: State.find_by(description:'Atlántico').id)
City.create(description:'SOLEDAD', state_id: State.find_by(description:'Atlántico').id)
City.create(description:'SUAN', state_id: State.find_by(description:'Atlántico').id)
City.create(description:'TUBARÁ', state_id: State.find_by(description:'Atlántico').id)
City.create(description:'USIACURÍ', state_id: State.find_by(description:'Atlántico').id)
City.create(description:'ACHÍ', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'ALTOS DEL ROSARIO', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'ARENAL', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'ARJONA', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'ARROYOHONDO', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'BARRANCO DE LOBA', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'CALAMAR', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'CANTAGALLO', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'CICUCO', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'CLEMENCIA', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'CÓRDOBA', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'EL CARMEN DE BOLÍVAR', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'EL GUAMO', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'EL PEÑÓN', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'HATILLO DE LOBA', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'MAGANGUÉ', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'MAHATES', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'MARGARITA', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'MARÍA LA BAJA', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'MOMPÓS', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'MONTECRISTO', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'MORALES', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'PINILLOS', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'REGIDOR', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'RÍO VIEJO', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'SAN CRISTÓBAL', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'SAN ESTANISLAO', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'SAN FERNANDO', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'SAN JACINTO', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'SAN JACINTO DEL CAUCA', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'SAN JUAN NEPOMUCENO', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'SAN MARTÍN DE LOBA', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'SAN PABLO', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'SANTA CATALINA', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'SANTA ROSA', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'SANTA ROSA DEL SUR', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'SIMITÍ', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'SOPLAVIENTO', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'TALAIGUA NUEVO', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'TIQUISIO', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'TURBACO', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'TURBANÁ', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'VILLANUEVA', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'ZAMBRANO', state_id: State.find_by(description:'Bolívar').id)
City.create(description:'ALMEIDA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'AQUITANIA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'ARCABUCO', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'BELÉN', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'BERBEO', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'BETÉITIVA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'BOAVITA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'BOYACÁ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'BRICEÑO', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'BUENAVISTA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'BUSBANZÁ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'CALDAS', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'CAMPOHERMOSO', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'CERINZA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'CHINAVITA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'CHIQUINQUIRÁ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'CHÍQUIZA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'CHISCAS', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'CHITA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'CHITARAQUE', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'CHIVATÁ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'CHIVOR', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'CIÉNEGA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'CÓMBITA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'COPER', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'CORRALES', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'COVARACHÍA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'CUBARÁ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'CUCAITA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'CUÍTIVA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'DUITAMA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'EL COCUY', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'EL ESPINO', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'FIRAVITOBA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'FLORESTA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'GACHANTIVÁ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'GAMEZA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'GARAGOA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'GUACAMAYAS', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'GUATEQUE', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'GUAYATÁ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'GÜICÁN', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'IZA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'JENESANO', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'JERICÓ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'LA CAPILLA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'LA UVITA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'LA VICTORIA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'LABRANZAGRANDE', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'MACANAL', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'MARIPÍ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'MIRAFLORES', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'MONGUA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'MONGUÍ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'MONIQUIRÁ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'MOTAVITA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'MUZO', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'NOBSA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'NUEVO COLÓN', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'OICATÁ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'OTANCHE', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'PACHAVITA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'PÁEZ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'PAIPA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'PAJARITO', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'PANQUEBA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'PAUNA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'PAYA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'PAZ DE RÍO', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'PESCA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'PISBA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'PUERTO BOYACÁ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'QUÍPAMA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'RAMIRIQUÍ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'RÁQUIRA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'RONDÓN', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SABOYÁ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SÁCHICA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SAMACÁ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SAN EDUARDO', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SAN JOSÉ DE PARE', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SAN LUIS DE GACENO', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SAN MATEO', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SAN MIGUEL DE SEMA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SAN PABLO DE BORBUR', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SANTA MARÍA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SANTA ROSA DE VITERBO', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SANTA SOFÍA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SANTANA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SATIVANORTE', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SATIVASUR', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SIACHOQUE', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SOATÁ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SOCHA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SOCOTÁ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SOGAMOSO', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SOMONDOCO', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SORA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SORACÁ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SOTAQUIRÁ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SUSACÓN', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SUTAMARCHÁN', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'SUTATENZA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'TASCO', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'TENZA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'TIBANÁ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'TIBASOSA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'TINJACÁ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'TIPACOQUE', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'TOCA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'TOGÜÍ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'TÓPAGA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'TOTA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'TUNJA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'TUNUNGUÁ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'TURMEQUÉ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'TUTA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'TUTAZÁ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'UMBITA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'VENTAQUEMADA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'VILLA DE LEYVA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'VIRACACHÁ', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'ZETAQUIRA', state_id: State.find_by(description:'Boyacá').id)
City.create(description:'AGUADAS', state_id: State.find_by(description:'Caldas').id)
City.create(description:'ANSERMA', state_id: State.find_by(description:'Caldas').id)
City.create(description:'ARANZAZU', state_id: State.find_by(description:'Caldas').id)
City.create(description:'BELALCÁZAR', state_id: State.find_by(description:'Caldas').id)
City.create(description:'CHINCHINÁ', state_id: State.find_by(description:'Caldas').id)
City.create(description:'FILADELFIA', state_id: State.find_by(description:'Caldas').id)
City.create(description:'LA DORADA', state_id: State.find_by(description:'Caldas').id)
City.create(description:'LA MERCED', state_id: State.find_by(description:'Caldas').id)
City.create(description:'MANIZALES', state_id: State.find_by(description:'Caldas').id)
City.create(description:'MANZANARES', state_id: State.find_by(description:'Caldas').id)
City.create(description:'MARMATO', state_id: State.find_by(description:'Caldas').id)
City.create(description:'MARQUETALIA', state_id: State.find_by(description:'Caldas').id)
City.create(description:'MARULANDA', state_id: State.find_by(description:'Caldas').id)
City.create(description:'NEIRA', state_id: State.find_by(description:'Caldas').id)
City.create(description:'NORCASIA', state_id: State.find_by(description:'Caldas').id)
City.create(description:'PÁCORA', state_id: State.find_by(description:'Caldas').id)
City.create(description:'PALESTINA', state_id: State.find_by(description:'Caldas').id)
City.create(description:'PENSILVANIA', state_id: State.find_by(description:'Caldas').id)
City.create(description:'RIOSUCIO', state_id: State.find_by(description:'Caldas').id)
City.create(description:'RISARALDA', state_id: State.find_by(description:'Caldas').id)
City.create(description:'SALAMINA', state_id: State.find_by(description:'Caldas').id)
City.create(description:'SAMANÁ', state_id: State.find_by(description:'Caldas').id)
City.create(description:'SAN JOSÉ', state_id: State.find_by(description:'Caldas').id)
City.create(description:'SUPÍA', state_id: State.find_by(description:'Caldas').id)
City.create(description:'VICTORIA', state_id: State.find_by(description:'Caldas').id)
City.create(description:'VILLAMARÍA', state_id: State.find_by(description:'Caldas').id)
City.create(description:'VITERBO', state_id: State.find_by(description:'Caldas').id)
City.create(description:'ALBANIA', state_id: State.find_by(description:'Caquetá').id)
City.create(description:'BELÉN DE LOS ANDAQUÍES', state_id: State.find_by(description:'Caquetá').id)
City.create(description:'CARTAGENA DEL CHAIRÁ', state_id: State.find_by(description:'Caquetá').id)
City.create(description:'CURILLO', state_id: State.find_by(description:'Caquetá').id)
City.create(description:'EL DONCELLO', state_id: State.find_by(description:'Caquetá').id)
City.create(description:'EL PAUJIL', state_id: State.find_by(description:'Caquetá').id)
City.create(description:'FLORENCIA', state_id: State.find_by(description:'Caquetá').id)
City.create(description:'LA MONTAÑITA', state_id: State.find_by(description:'Caquetá').id)
City.create(description:'MILÁN', state_id: State.find_by(description:'Caquetá').id)
City.create(description:'MORELIA', state_id: State.find_by(description:'Caquetá').id)
City.create(description:'PUERTO RICO', state_id: State.find_by(description:'Caquetá').id)
City.create(description:'SAN JOSÉ DEL FRAGUA', state_id: State.find_by(description:'Caquetá').id)
City.create(description:'SAN VICENTE DEL CAGUÁN', state_id: State.find_by(description:'Caquetá').id)
City.create(description:'SOLANO', state_id: State.find_by(description:'Caquetá').id)
City.create(description:'SOLITA', state_id: State.find_by(description:'Caquetá').id)
City.create(description:'VALPARAÍSO', state_id: State.find_by(description:'Caquetá').id)
City.create(description:'AGUAZUL', state_id: State.find_by(description:'Casanare').id)
City.create(description:'CHAMEZA', state_id: State.find_by(description:'Casanare').id)
City.create(description:'HATO COROZAL', state_id: State.find_by(description:'Casanare').id)
City.create(description:'LA SALINA', state_id: State.find_by(description:'Casanare').id)
City.create(description:'MANÍ', state_id: State.find_by(description:'Casanare').id)
City.create(description:'MONTERREY', state_id: State.find_by(description:'Casanare').id)
City.create(description:'NUNCHÍA', state_id: State.find_by(description:'Casanare').id)
City.create(description:'OROCUÉ', state_id: State.find_by(description:'Casanare').id)
City.create(description:'PAZ DE ARIPORO', state_id: State.find_by(description:'Casanare').id)
City.create(description:'PORE', state_id: State.find_by(description:'Casanare').id)
City.create(description:'RECETOR', state_id: State.find_by(description:'Casanare').id)
City.create(description:'SABANALARGA', state_id: State.find_by(description:'Casanare').id)
City.create(description:'SÁCAMA', state_id: State.find_by(description:'Casanare').id)
City.create(description:'SAN LUIS DE PALENQUE', state_id: State.find_by(description:'Casanare').id)
City.create(description:'TÁMARA', state_id: State.find_by(description:'Casanare').id)
City.create(description:'TAURAMENA', state_id: State.find_by(description:'Casanare').id)
City.create(description:'TRINIDAD', state_id: State.find_by(description:'Casanare').id)
City.create(description:'VILLANUEVA', state_id: State.find_by(description:'Casanare').id)
City.create(description:'ALMAGUER', state_id: State.find_by(description:'Cauca').id)
City.create(description:'ARGELIA', state_id: State.find_by(description:'Cauca').id)
City.create(description:'BALBOA', state_id: State.find_by(description:'Cauca').id)
City.create(description:'BOLÍVAR', state_id: State.find_by(description:'Cauca').id)
City.create(description:'BUENOS AIRES', state_id: State.find_by(description:'Cauca').id)
City.create(description:'CAJIBÍO', state_id: State.find_by(description:'Cauca').id)
City.create(description:'CALDONO', state_id: State.find_by(description:'Cauca').id)
City.create(description:'CALOTO', state_id: State.find_by(description:'Cauca').id)
City.create(description:'CORINTO', state_id: State.find_by(description:'Cauca').id)
City.create(description:'EL TAMBO', state_id: State.find_by(description:'Cauca').id)
City.create(description:'FLORENCIA', state_id: State.find_by(description:'Cauca').id)
City.create(description:'GUACHENÉ', state_id: State.find_by(description:'Cauca').id)
City.create(description:'GUAPI', state_id: State.find_by(description:'Cauca').id)
City.create(description:'INZÁ', state_id: State.find_by(description:'Cauca').id)
City.create(description:'JAMBALÓ', state_id: State.find_by(description:'Cauca').id)
City.create(description:'LA SIERRA', state_id: State.find_by(description:'Cauca').id)
City.create(description:'LA VEGA', state_id: State.find_by(description:'Cauca').id)
City.create(description:'LÓPEZ', state_id: State.find_by(description:'Cauca').id)
City.create(description:'MERCADERES', state_id: State.find_by(description:'Cauca').id)
City.create(description:'MIRANDA', state_id: State.find_by(description:'Cauca').id)
City.create(description:'MORALES', state_id: State.find_by(description:'Cauca').id)
City.create(description:'PADILLA', state_id: State.find_by(description:'Cauca').id)
City.create(description:'PAEZ', state_id: State.find_by(description:'Cauca').id)
City.create(description:'PATÍA', state_id: State.find_by(description:'Cauca').id)
City.create(description:'PIAMONTE', state_id: State.find_by(description:'Cauca').id)
City.create(description:'PIENDAMÓ', state_id: State.find_by(description:'Cauca').id)
City.create(description:'POPAYÁN', state_id: State.find_by(description:'Cauca').id)
City.create(description:'PUERTO TEJADA', state_id: State.find_by(description:'Cauca').id)
City.create(description:'PURACÉ', state_id: State.find_by(description:'Cauca').id)
City.create(description:'ROSAS', state_id: State.find_by(description:'Cauca').id)
City.create(description:'SAN SEBASTIÁN', state_id: State.find_by(description:'Cauca').id)
City.create(description:'SANTA ROSA', state_id: State.find_by(description:'Cauca').id)
City.create(description:'SANTANDER DE QUILICHAO', state_id: State.find_by(description:'Cauca').id)
City.create(description:'SILVIA', state_id: State.find_by(description:'Cauca').id)
City.create(description:'SOTARA', state_id: State.find_by(description:'Cauca').id)
City.create(description:'SOTARÁ', state_id: State.find_by(description:'Cauca').id)
City.create(description:'SUÁREZ', state_id: State.find_by(description:'Cauca').id)
City.create(description:'SUCRE', state_id: State.find_by(description:'Cauca').id)
City.create(description:'TIMBÍO', state_id: State.find_by(description:'Cauca').id)
City.create(description:'TIMBIQUÍ', state_id: State.find_by(description:'Cauca').id)
City.create(description:'TORIBIO', state_id: State.find_by(description:'Cauca').id)
City.create(description:'TOTORÓ', state_id: State.find_by(description:'Cauca').id)
City.create(description:'VILLA RICA', state_id: State.find_by(description:'Cauca').id)
City.create(description:'AGUACHICA', state_id: State.find_by(description:'Cesar').id)
City.create(description:'AGUSTÍN CODAZZI', state_id: State.find_by(description:'Cesar').id)
City.create(description:'ASTREA', state_id: State.find_by(description:'Cesar').id)
City.create(description:'BECERRIL', state_id: State.find_by(description:'Cesar').id)
City.create(description:'BOSCONIA', state_id: State.find_by(description:'Cesar').id)
City.create(description:'CHIMICHAGUA', state_id: State.find_by(description:'Cesar').id)
City.create(description:'CHIRIGUANÁ', state_id: State.find_by(description:'Cesar').id)
City.create(description:'CURUMANÍ', state_id: State.find_by(description:'Cesar').id)
City.create(description:'EL COPEY', state_id: State.find_by(description:'Cesar').id)
City.create(description:'EL PASO', state_id: State.find_by(description:'Cesar').id)
City.create(description:'GAMARRA', state_id: State.find_by(description:'Cesar').id)
City.create(description:'GONZÁLEZ', state_id: State.find_by(description:'Cesar').id)
City.create(description:'LA GLORIA', state_id: State.find_by(description:'Cesar').id)
City.create(description:'LA JAGUA DE IBIRICO', state_id: State.find_by(description:'Cesar').id)
City.create(description:'LA PAZ', state_id: State.find_by(description:'Cesar').id)
City.create(description:'MANAURE', state_id: State.find_by(description:'Cesar').id)
City.create(description:'PAILITAS', state_id: State.find_by(description:'Cesar').id)
City.create(description:'PELAYA', state_id: State.find_by(description:'Cesar').id)
City.create(description:'PUEBLO BELLO', state_id: State.find_by(description:'Cesar').id)
City.create(description:'RÍO DE ORO', state_id: State.find_by(description:'Cesar').id)
City.create(description:'SAN ALBERTO', state_id: State.find_by(description:'Cesar').id)
City.create(description:'SAN DIEGO', state_id: State.find_by(description:'Cesar').id)
City.create(description:'SAN MARTÍN', state_id: State.find_by(description:'Cesar').id)
City.create(description:'TAMALAMEQUE', state_id: State.find_by(description:'Cesar').id)
City.create(description:'VALLEDUPAR', state_id: State.find_by(description:'Cesar').id)
City.create(description:'ACANDÍ', state_id: State.find_by(description:'Chocó').id)
City.create(description:'ALTO BAUDÓ', state_id: State.find_by(description:'Chocó').id)
City.create(description:'ATRATO', state_id: State.find_by(description:'Chocó').id)
City.create(description:'BAGADÓ', state_id: State.find_by(description:'Chocó').id)
City.create(description:'BAHÍA SOLANO', state_id: State.find_by(description:'Chocó').id)
City.create(description:'BAJO BAUDÓ', state_id: State.find_by(description:'Chocó').id)
City.create(description:'BELÉN DE BAJIRÁ', state_id: State.find_by(description:'Chocó').id)
City.create(description:'BOJAYA', state_id: State.find_by(description:'Chocó').id)
City.create(description:'CARMEN DEL DARIEN', state_id: State.find_by(description:'Chocó').id)
City.create(description:'CÉRTEGUI', state_id: State.find_by(description:'Chocó').id)
City.create(description:'CONDOTO', state_id: State.find_by(description:'Chocó').id)
City.create(description:'EL CANTÓN DEL SAN PABLO', state_id: State.find_by(description:'Chocó').id)
City.create(description:'EL CARMEN DE ATRATO', state_id: State.find_by(description:'Chocó').id)
City.create(description:'EL LITORAL DEL SAN JUAN', state_id: State.find_by(description:'Chocó').id)
City.create(description:'ISTMINA', state_id: State.find_by(description:'Chocó').id)
City.create(description:'JURADÓ', state_id: State.find_by(description:'Chocó').id)
City.create(description:'LLORÓ', state_id: State.find_by(description:'Chocó').id)
City.create(description:'MEDIO ATRATO', state_id: State.find_by(description:'Chocó').id)
City.create(description:'MEDIO BAUDÓ', state_id: State.find_by(description:'Chocó').id)
City.create(description:'MEDIO SAN JUAN', state_id: State.find_by(description:'Chocó').id)
City.create(description:'NÓVITA', state_id: State.find_by(description:'Chocó').id)
City.create(description:'NUQUÍ', state_id: State.find_by(description:'Chocó').id)
City.create(description:'QUIBDÓ', state_id: State.find_by(description:'Chocó').id)
City.create(description:'RÍO IRÓ', state_id: State.find_by(description:'Chocó').id)
City.create(description:'RÍO QUITO', state_id: State.find_by(description:'Chocó').id)
City.create(description:'RIOSUCIO', state_id: State.find_by(description:'Chocó').id)
City.create(description:'SAN JOSÉ DEL PALMAR', state_id: State.find_by(description:'Chocó').id)
City.create(description:'SIPÍ', state_id: State.find_by(description:'Chocó').id)
City.create(description:'TADÓ', state_id: State.find_by(description:'Chocó').id)
City.create(description:'UNGUÍA', state_id: State.find_by(description:'Chocó').id)
City.create(description:'UNIÓN PANAMERICANA', state_id: State.find_by(description:'Chocó').id)
City.create(description:'AYAPEL', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'BUENAVISTA', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'CANALETE', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'CERETÉ', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'CHIMÁ', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'CHINÚ', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'CIÉNAGA DE ORO', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'COTORRA', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'LA APARTADA', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'LORICA', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'LOS CÓRDOBAS', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'MOMIL', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'MONTELÍBANO', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'MONTERÍA', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'MOÑITOS', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'PLANETA RICA', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'PUEBLO NUEVO', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'PUERTO ESCONDIDO', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'PUERTO LIBERTADOR', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'PURÍSIMA', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'SAHAGÚN', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'SAN ANDRÉS SOTAVENTO', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'SAN ANTERO', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'SAN BERNARDO DEL VIENTO', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'SAN CARLOS', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'SAN PELAYO', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'TIERRALTA', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'VALENCIA', state_id: State.find_by(description:'Córdoba').id)
City.create(description:'AGUA DE DIOS', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'ANOLAIMA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'APULO', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'ARBELÁEZ', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'BELTRÁN', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'BITUIMA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'BOJACÁ', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'CABRERA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'CACHIPAY', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'CAPARRAPÍ', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'CAQUEZA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'CARMEN DE CARUPA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'CHAGUANÍ', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'CHIPAQUE', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'CHOACHÍ', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'CHOCONTÁ', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'CUCUNUBÁ', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'EL PEÑÓN', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'EL ROSAL', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'FOMEQUE', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'FOSCA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'FÚQUENE', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'GACHALA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'GACHANCIPÁ', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'GACHETÁ', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'GAMA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'GRANADA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'GUACHETÁ', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'GUADUAS', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'GUATAQUÍ', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'GUAYABAL DE SIQUIMA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'GUAYABETAL', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'GUTIÉRREZ', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'JERUSALÉN', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'JUNÍN', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'LA CALERA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'LA PALMA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'LA PEÑA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'LA VEGA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'LENGUAZAQUE', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'MACHETA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'MANTA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'MEDINA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'NARIÑO', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'NEMOCÓN', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'NILO', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'NIMAIMA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'NOCAIMA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'PACHO', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'PAIME', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'PANDI', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'PARATEBUENO', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'PASCA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'PUERTO SALGAR', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'PULÍ', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'QUEBRADANEGRA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'QUETAME', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'QUIPILE', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'SAN ANTONIO DEL TEQUENDAMA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'SAN BERNARDO', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'SAN CAYETANO', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'SAN FRANCISCO', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'SAN JUAN DE RÍO SECO', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'SASAIMA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'SIBATÉ', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'SILVANIA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'SIMIJACA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'SUBACHOQUE', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'SUESCA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'SUPATÁ', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'SUSA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'SUTATAUSA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'TAUSA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'TENA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'TENJO', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'TIBACUY', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'TIBIRITA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'TOCAIMA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'TOPAIPÍ', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'UBALÁ', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'UBAQUE', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'UNE', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'ÚTICA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'VENECIA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'VERGARA', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'VIANÍ', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'VILLAGÓMEZ', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'VILLAPINZÓN', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'VIOTÁ', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'YACOPÍ', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'ZIPACÓN', state_id: State.find_by(description:'Cundinamarca').id)
City.create(description:'BARRANCO MINAS', state_id: State.find_by(description:'Guainía').id)
City.create(description:'CACAHUAL', state_id: State.find_by(description:'Guainía').id)
City.create(description:'INÍRIDA', state_id: State.find_by(description:'Guainía').id)
City.create(description:'LA GUADALUPE', state_id: State.find_by(description:'Guainía').id)
City.create(description:'MAPIRIPANA', state_id: State.find_by(description:'Guainía').id)
City.create(description:'MORICHAL', state_id: State.find_by(description:'Guainía').id)
City.create(description:'PANA PANA', state_id: State.find_by(description:'Guainía').id)
City.create(description:'PUERTO COLOMBIA', state_id: State.find_by(description:'Guainía').id)
City.create(description:'SAN FELIPE', state_id: State.find_by(description:'Guainía').id)
City.create(description:'CALAMAR', state_id: State.find_by(description:'Guaviare').id)
City.create(description:'EL RETORNO', state_id: State.find_by(description:'Guaviare').id)
City.create(description:'MIRAFLORES', state_id: State.find_by(description:'Guaviare').id)
City.create(description:'SAN JOSÉ DEL GUAVIARE', state_id: State.find_by(description:'Guaviare').id)
City.create(description:'ACEVEDO', state_id: State.find_by(description:'Huila').id)
City.create(description:'AGRADO', state_id: State.find_by(description:'Huila').id)
City.create(description:'AIPE', state_id: State.find_by(description:'Huila').id)
City.create(description:'ALGECIRAS', state_id: State.find_by(description:'Huila').id)
City.create(description:'ALTAMIRA', state_id: State.find_by(description:'Huila').id)
City.create(description:'BARAYA', state_id: State.find_by(description:'Huila').id)
City.create(description:'CAMPOALEGRE', state_id: State.find_by(description:'Huila').id)
City.create(description:'COLOMBIA', state_id: State.find_by(description:'Huila').id)
City.create(description:'ELÍAS', state_id: State.find_by(description:'Huila').id)
City.create(description:'GARZÓN', state_id: State.find_by(description:'Huila').id)
City.create(description:'GIGANTE', state_id: State.find_by(description:'Huila').id)
City.create(description:'GUADALUPE', state_id: State.find_by(description:'Huila').id)
City.create(description:'HOBO', state_id: State.find_by(description:'Huila').id)
City.create(description:'IQUIRA', state_id: State.find_by(description:'Huila').id)
City.create(description:'ISNOS', state_id: State.find_by(description:'Huila').id)
City.create(description:'LA ARGENTINA', state_id: State.find_by(description:'Huila').id)
City.create(description:'LA PLATA', state_id: State.find_by(description:'Huila').id)
City.create(description:'NÁTAGA', state_id: State.find_by(description:'Huila').id)
City.create(description:'NEIVA', state_id: State.find_by(description:'Huila').id)
City.create(description:'OPORAPA', state_id: State.find_by(description:'Huila').id)
City.create(description:'PAICOL', state_id: State.find_by(description:'Huila').id)
City.create(description:'PALERMO', state_id: State.find_by(description:'Huila').id)
City.create(description:'PALESTINA', state_id: State.find_by(description:'Huila').id)
City.create(description:'PITAL', state_id: State.find_by(description:'Huila').id)
City.create(description:'PITALITO', state_id: State.find_by(description:'Huila').id)
City.create(description:'RIVERA', state_id: State.find_by(description:'Huila').id)
City.create(description:'SALADOBLANCO', state_id: State.find_by(description:'Huila').id)
City.create(description:'SAN AGUSTÍN', state_id: State.find_by(description:'Huila').id)
City.create(description:'SANTA MARÍA', state_id: State.find_by(description:'Huila').id)
City.create(description:'SUAZA', state_id: State.find_by(description:'Huila').id)
City.create(description:'TARQUI', state_id: State.find_by(description:'Huila').id)
City.create(description:'TELLO', state_id: State.find_by(description:'Huila').id)
City.create(description:'TERUEL', state_id: State.find_by(description:'Huila').id)
City.create(description:'TESALIA', state_id: State.find_by(description:'Huila').id)
City.create(description:'TIMANÁ', state_id: State.find_by(description:'Huila').id)
City.create(description:'VILLAVIEJA', state_id: State.find_by(description:'Huila').id)
City.create(description:'YAGUARÁ', state_id: State.find_by(description:'Huila').id)
City.create(description:'ALBANIA', state_id: State.find_by(description:'La Guajira').id)
City.create(description:'BARRANCAS', state_id: State.find_by(description:'La Guajira').id)
City.create(description:'DIBULLA', state_id: State.find_by(description:'La Guajira').id)
City.create(description:'DISTRACCIÓN', state_id: State.find_by(description:'La Guajira').id)
City.create(description:'EL MOLINO', state_id: State.find_by(description:'La Guajira').id)
City.create(description:'FONSECA', state_id: State.find_by(description:'La Guajira').id)
City.create(description:'HATO NUEVO', state_id: State.find_by(description:'La Guajira').id)
City.create(description:'LA JAGUA DEL PILAR', state_id: State.find_by(description:'La Guajira').id)
City.create(description:'MAICAO', state_id: State.find_by(description:'La Guajira').id)
City.create(description:'MANAURE', state_id: State.find_by(description:'La Guajira').id)
City.create(description:'RIOHACHA', state_id: State.find_by(description:'La Guajira').id)
City.create(description:'SAN JUAN DEL CESAR', state_id: State.find_by(description:'La Guajira').id)
City.create(description:'URIBIA', state_id: State.find_by(description:'La Guajira').id)
City.create(description:'URUMITA', state_id: State.find_by(description:'La Guajira').id)
City.create(description:'VILLANUEVA', state_id: State.find_by(description:'La Guajira').id)
City.create(description:'ALGARROBO', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'ARACATACA', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'ARIGUANÍ', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'CERRO SAN ANTONIO', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'CHIBOLO', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'CIÉNAGA', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'CONCORDIA', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'EL BANCO', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'EL PIÑON', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'EL RETÉN', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'FUNDACIÓN', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'GUAMAL', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'NUEVA GRANADA', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'PEDRAZA', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'PIJIÑO DEL CARMEN', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'PIVIJAY', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'PLATO', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'PUEBLOVIEJO', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'REMOLINO', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'SABANAS DE SAN ANGEL', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'SALAMINA', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'SAN SEBASTIÁN DE BUENAVISTA', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'SAN ZENÓN', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'SANTA ANA', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'SANTA BÁRBARA DE PINTO', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'SITIONUEVO', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'TENERIFE', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'ZAPAYÁN', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'ZONA BANANERA', state_id: State.find_by(description:'Magdalena').id)
City.create(description:'ACACÍAS', state_id: State.find_by(description:'Meta').id)
City.create(description:'BARRANCA DE UPÍA', state_id: State.find_by(description:'Meta').id)
City.create(description:'CABUYARO', state_id: State.find_by(description:'Meta').id)
City.create(description:'CASTILLA LA NUEVA', state_id: State.find_by(description:'Meta').id)
City.create(description:'CUBARRAL', state_id: State.find_by(description:'Meta').id)
City.create(description:'CUMARAL', state_id: State.find_by(description:'Meta').id)
City.create(description:'EL CALVARIO', state_id: State.find_by(description:'Meta').id)
City.create(description:'EL CASTILLO', state_id: State.find_by(description:'Meta').id)
City.create(description:'EL DORADO', state_id: State.find_by(description:'Meta').id)
City.create(description:'FUENTE DE ORO', state_id: State.find_by(description:'Meta').id)
City.create(description:'GRANADA', state_id: State.find_by(description:'Meta').id)
City.create(description:'GUAMAL', state_id: State.find_by(description:'Meta').id)
City.create(description:'LA MACARENA', state_id: State.find_by(description:'Meta').id)
City.create(description:'LEJANÍAS', state_id: State.find_by(description:'Meta').id)
City.create(description:'MAPIRIPÁN', state_id: State.find_by(description:'Meta').id)
City.create(description:'MESETAS', state_id: State.find_by(description:'Meta').id)
City.create(description:'PUERTO CONCORDIA', state_id: State.find_by(description:'Meta').id)
City.create(description:'PUERTO GAITÁN', state_id: State.find_by(description:'Meta').id)
City.create(description:'PUERTO LLERAS', state_id: State.find_by(description:'Meta').id)
City.create(description:'PUERTO LÓPEZ', state_id: State.find_by(description:'Meta').id)
City.create(description:'PUERTO RICO', state_id: State.find_by(description:'Meta').id)
City.create(description:'RESTREPO', state_id: State.find_by(description:'Meta').id)
City.create(description:'SAN CARLOS DE GUAROA', state_id: State.find_by(description:'Meta').id)
City.create(description:'SAN JUAN DE ARAMA', state_id: State.find_by(description:'Meta').id)
City.create(description:'SAN JUANITO', state_id: State.find_by(description:'Meta').id)
City.create(description:'SAN MARTÍN', state_id: State.find_by(description:'Meta').id)
City.create(description:'URIBE', state_id: State.find_by(description:'Meta').id)
City.create(description:'VILLAVICENCIO', state_id: State.find_by(description:'Meta').id)
City.create(description:'VISTA HERMOSA', state_id: State.find_by(description:'Meta').id)
City.create(description:'ALDANA', state_id: State.find_by(description:'Nariño').id)
City.create(description:'ANCUYÁ', state_id: State.find_by(description:'Nariño').id)
City.create(description:'ARBOLEDA', state_id: State.find_by(description:'Nariño').id)
City.create(description:'BARBACOAS', state_id: State.find_by(description:'Nariño').id)
City.create(description:'BELÉN', state_id: State.find_by(description:'Nariño').id)
City.create(description:'BUESACO', state_id: State.find_by(description:'Nariño').id)
City.create(description:'CHACHAGÜÍ', state_id: State.find_by(description:'Nariño').id)
City.create(description:'COLÓN', state_id: State.find_by(description:'Nariño').id)
City.create(description:'CONSACA', state_id: State.find_by(description:'Nariño').id)
City.create(description:'CONTADERO', state_id: State.find_by(description:'Nariño').id)
City.create(description:'CÓRDOBA', state_id: State.find_by(description:'Nariño').id)
City.create(description:'CUASPUD', state_id: State.find_by(description:'Nariño').id)
City.create(description:'CUMBAL', state_id: State.find_by(description:'Nariño').id)
City.create(description:'CUMBITARA', state_id: State.find_by(description:'Nariño').id)
City.create(description:'EL CHARCO', state_id: State.find_by(description:'Nariño').id)
City.create(description:'EL PEÑOL', state_id: State.find_by(description:'Nariño').id)
City.create(description:'EL ROSARIO', state_id: State.find_by(description:'Nariño').id)
City.create(description:'EL TABLÓN DE GÓMEZ', state_id: State.find_by(description:'Nariño').id)
City.create(description:'EL TAMBO', state_id: State.find_by(description:'Nariño').id)
City.create(description:'FRANCISCO PIZARRO', state_id: State.find_by(description:'Nariño').id)
City.create(description:'FUNES', state_id: State.find_by(description:'Nariño').id)
City.create(description:'GUACHUCAL', state_id: State.find_by(description:'Nariño').id)
City.create(description:'GUAITARILLA', state_id: State.find_by(description:'Nariño').id)
City.create(description:'GUALMATÁN', state_id: State.find_by(description:'Nariño').id)
City.create(description:'ILES', state_id: State.find_by(description:'Nariño').id)
City.create(description:'IMUÉS', state_id: State.find_by(description:'Nariño').id)
City.create(description:'IPIALES', state_id: State.find_by(description:'Nariño').id)
City.create(description:'LA CRUZ', state_id: State.find_by(description:'Nariño').id)
City.create(description:'LA FLORIDA', state_id: State.find_by(description:'Nariño').id)
City.create(description:'LA LLANADA', state_id: State.find_by(description:'Nariño').id)
City.create(description:'LA TOLA', state_id: State.find_by(description:'Nariño').id)
City.create(description:'LA UNIÓN', state_id: State.find_by(description:'Nariño').id)
City.create(description:'LEIVA', state_id: State.find_by(description:'Nariño').id)
City.create(description:'LINARES', state_id: State.find_by(description:'Nariño').id)
City.create(description:'LOS ANDES', state_id: State.find_by(description:'Nariño').id)
City.create(description:'MAGÜI', state_id: State.find_by(description:'Nariño').id)
City.create(description:'MALLAMA', state_id: State.find_by(description:'Nariño').id)
City.create(description:'MOSQUERA', state_id: State.find_by(description:'Nariño').id)
City.create(description:'NARIÑO', state_id: State.find_by(description:'Nariño').id)
City.create(description:'OLAYA HERRERA', state_id: State.find_by(description:'Nariño').id)
City.create(description:'OSPINA', state_id: State.find_by(description:'Nariño').id)
City.create(description:'PASTO', state_id: State.find_by(description:'Nariño').id)
City.create(description:'POLICARPA', state_id: State.find_by(description:'Nariño').id)
City.create(description:'POTOSÍ', state_id: State.find_by(description:'Nariño').id)
City.create(description:'PROVIDENCIA', state_id: State.find_by(description:'Nariño').id)
City.create(description:'PUERRES', state_id: State.find_by(description:'Nariño').id)
City.create(description:'PUPIALES', state_id: State.find_by(description:'Nariño').id)
City.create(description:'RICAURTE', state_id: State.find_by(description:'Nariño').id)
City.create(description:'ROBERTO PAYÁN', state_id: State.find_by(description:'Nariño').id)
City.create(description:'SAMANIEGO', state_id: State.find_by(description:'Nariño').id)
City.create(description:'SAN ANDRES DE TUMACO', state_id: State.find_by(description:'Nariño').id)
City.create(description:'SAN BERNARDO', state_id: State.find_by(description:'Nariño').id)
City.create(description:'SAN LORENZO', state_id: State.find_by(description:'Nariño').id)
City.create(description:'SAN PABLO', state_id: State.find_by(description:'Nariño').id)
City.create(description:'SAN PEDRO DE CARTAGO', state_id: State.find_by(description:'Nariño').id)
City.create(description:'SANDONÁ', state_id: State.find_by(description:'Nariño').id)
City.create(description:'SANTA BÁRBARA', state_id: State.find_by(description:'Nariño').id)
City.create(description:'SANTACRUZ', state_id: State.find_by(description:'Nariño').id)
City.create(description:'SAPUYES', state_id: State.find_by(description:'Nariño').id)
City.create(description:'TAMINANGO', state_id: State.find_by(description:'Nariño').id)
City.create(description:'TANGUA', state_id: State.find_by(description:'Nariño').id)
City.create(description:'TÚQUERRES', state_id: State.find_by(description:'Nariño').id)
City.create(description:'YACUANQUER', state_id: State.find_by(description:'Nariño').id)
City.create(description:'ABREGO', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'ARBOLEDAS', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'BOCHALEMA', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'BUCARASICA', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'CACHIRÁ', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'CÁCOTA', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'CHINÁCOTA', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'CHITAGÁ', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'CONVENCIÓN', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'CÚCUTA', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'CUCUTILLA', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'DURANIA', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'EL CARMEN', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'EL TARRA', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'EL ZULIA', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'GRAMALOTE', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'HACARÍ', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'HERRÁN', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'LA ESPERANZA', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'LA PLAYA', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'LABATECA', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'LOS PATIOS', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'LOURDES', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'MUTISCUA', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'OCAÑA', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'PAMPLONA', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'PAMPLONITA', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'PUERTO SANTANDER', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'RAGONVALIA', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'SALAZAR', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'SAN CALIXTO', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'SAN CAYETANO', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'SANTIAGO', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'SARDINATA', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'SILOS', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'TEORAMA', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'TIBÚ', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'TOLEDO', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'VILLA CARO', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'VILLA DEL ROSARIO', state_id: State.find_by(description:'Norte de Santander').id)
City.create(description:'COLÓN', state_id: State.find_by(description:'Putumayo').id)
City.create(description:'LEGUÍZAMO', state_id: State.find_by(description:'Putumayo').id)
City.create(description:'MOCOA', state_id: State.find_by(description:'Putumayo').id)
City.create(description:'ORITO', state_id: State.find_by(description:'Putumayo').id)
City.create(description:'PUERTO ASÍS', state_id: State.find_by(description:'Putumayo').id)
City.create(description:'PUERTO CAICEDO', state_id: State.find_by(description:'Putumayo').id)
City.create(description:'PUERTO GUZMÁN', state_id: State.find_by(description:'Putumayo').id)
City.create(description:'SAN FRANCISCO', state_id: State.find_by(description:'Putumayo').id)
City.create(description:'SAN MIGUEL', state_id: State.find_by(description:'Putumayo').id)
City.create(description:'SANTIAGO', state_id: State.find_by(description:'Putumayo').id)
City.create(description:'SIBUNDOY', state_id: State.find_by(description:'Putumayo').id)
City.create(description:'VALLE DEL GUAMUEZ', state_id: State.find_by(description:'Putumayo').id)
City.create(description:'VILLAGARZÓN', state_id: State.find_by(description:'Putumayo').id)
City.create(description:'ARMENIA', state_id: State.find_by(description:'Quindio').id)
City.create(description:'BUENAVISTA', state_id: State.find_by(description:'Quindio').id)
City.create(description:'CALARCA', state_id: State.find_by(description:'Quindio').id)
City.create(description:'CIRCASIA', state_id: State.find_by(description:'Quindio').id)
City.create(description:'CÓRDOBA', state_id: State.find_by(description:'Quindio').id)
City.create(description:'FILANDIA', state_id: State.find_by(description:'Quindio').id)
City.create(description:'GÉNOVA', state_id: State.find_by(description:'Quindio').id)
City.create(description:'LA TEBAIDA', state_id: State.find_by(description:'Quindio').id)
City.create(description:'MONTENEGRO', state_id: State.find_by(description:'Quindio').id)
City.create(description:'PIJAO', state_id: State.find_by(description:'Quindio').id)
City.create(description:'QUIMBAYA', state_id: State.find_by(description:'Quindio').id)
City.create(description:'SALENTO', state_id: State.find_by(description:'Quindio').id)
City.create(description:'APÍA', state_id: State.find_by(description:'Risaralda').id)
City.create(description:'BALBOA', state_id: State.find_by(description:'Risaralda').id)
City.create(description:'BELÉN DE UMBRÍA', state_id: State.find_by(description:'Risaralda').id)
City.create(description:'DOSQUEBRADAS', state_id: State.find_by(description:'Risaralda').id)
City.create(description:'GUÁTICA', state_id: State.find_by(description:'Risaralda').id)
City.create(description:'LA CELIA', state_id: State.find_by(description:'Risaralda').id)
City.create(description:'LA VIRGINIA', state_id: State.find_by(description:'Risaralda').id)
City.create(description:'MARSELLA', state_id: State.find_by(description:'Risaralda').id)
City.create(description:'MISTRATÓ', state_id: State.find_by(description:'Risaralda').id)
City.create(description:'PEREIRA', state_id: State.find_by(description:'Risaralda').id)
City.create(description:'PUEBLO RICO', state_id: State.find_by(description:'Risaralda').id)
City.create(description:'QUINCHÍA', state_id: State.find_by(description:'Risaralda').id)
City.create(description:'SANTA ROSA DE CABAL', state_id: State.find_by(description:'Risaralda').id)
City.create(description:'SANTUARIO', state_id: State.find_by(description:'Risaralda').id)
City.create(description:'AGUADA', state_id: State.find_by(description:'Santander').id)
City.create(description:'ALBANIA', state_id: State.find_by(description:'Santander').id)
City.create(description:'ARATOCA', state_id: State.find_by(description:'Santander').id)
City.create(description:'BARBOSA', state_id: State.find_by(description:'Santander').id)
City.create(description:'BARICHARA', state_id: State.find_by(description:'Santander').id)
City.create(description:'BARRANCABERMEJA', state_id: State.find_by(description:'Santander').id)
City.create(description:'BETULIA', state_id: State.find_by(description:'Santander').id)
City.create(description:'BOLÍVAR', state_id: State.find_by(description:'Santander').id)
City.create(description:'BUCARAMANGA', state_id: State.find_by(description:'Santander').id)
City.create(description:'CABRERA', state_id: State.find_by(description:'Santander').id)
City.create(description:'CALIFORNIA', state_id: State.find_by(description:'Santander').id)
City.create(description:'CAPITANEJO', state_id: State.find_by(description:'Santander').id)
City.create(description:'CARCASÍ', state_id: State.find_by(description:'Santander').id)
City.create(description:'CEPITÁ', state_id: State.find_by(description:'Santander').id)
City.create(description:'CERRITO', state_id: State.find_by(description:'Santander').id)
City.create(description:'CHARALÁ', state_id: State.find_by(description:'Santander').id)
City.create(description:'CHARTA', state_id: State.find_by(description:'Santander').id)
City.create(description:'CHIMA', state_id: State.find_by(description:'Santander').id)
City.create(description:'CHIPATÁ', state_id: State.find_by(description:'Santander').id)
City.create(description:'CIMITARRA', state_id: State.find_by(description:'Santander').id)
City.create(description:'CONCEPCIÓN', state_id: State.find_by(description:'Santander').id)
City.create(description:'CONFINES', state_id: State.find_by(description:'Santander').id)
City.create(description:'CONTRATACIÓN', state_id: State.find_by(description:'Santander').id)
City.create(description:'COROMORO', state_id: State.find_by(description:'Santander').id)
City.create(description:'CURITÍ', state_id: State.find_by(description:'Santander').id)
City.create(description:'EL CARMEN DE CHUCURÍ', state_id: State.find_by(description:'Santander').id)
City.create(description:'EL GUACAMAYO', state_id: State.find_by(description:'Santander').id)
City.create(description:'EL PEÑÓN', state_id: State.find_by(description:'Santander').id)
City.create(description:'EL PLAYÓN', state_id: State.find_by(description:'Santander').id)
City.create(description:'ENCINO', state_id: State.find_by(description:'Santander').id)
City.create(description:'ENCISO', state_id: State.find_by(description:'Santander').id)
City.create(description:'FLORIÁN', state_id: State.find_by(description:'Santander').id)
City.create(description:'FLORIDABLANCA', state_id: State.find_by(description:'Santander').id)
City.create(description:'GALÁN', state_id: State.find_by(description:'Santander').id)
City.create(description:'GAMBITA', state_id: State.find_by(description:'Santander').id)
City.create(description:'GIRÓN', state_id: State.find_by(description:'Santander').id)
City.create(description:'GUACA', state_id: State.find_by(description:'Santander').id)
City.create(description:'GUADALUPE', state_id: State.find_by(description:'Santander').id)
City.create(description:'GUAPOTÁ', state_id: State.find_by(description:'Santander').id)
City.create(description:'GUAVATÁ', state_id: State.find_by(description:'Santander').id)
City.create(description:'GÜEPSA', state_id: State.find_by(description:'Santander').id)
City.create(description:'HATO', state_id: State.find_by(description:'Santander').id)
City.create(description:'JESÚS MARÍA', state_id: State.find_by(description:'Santander').id)
City.create(description:'JORDÁN', state_id: State.find_by(description:'Santander').id)
City.create(description:'LA BELLEZA', state_id: State.find_by(description:'Santander').id)
City.create(description:'LA PAZ', state_id: State.find_by(description:'Santander').id)
City.create(description:'LANDÁZURI', state_id: State.find_by(description:'Santander').id)
City.create(description:'LEBRIJA', state_id: State.find_by(description:'Santander').id)
City.create(description:'LOS SANTOS', state_id: State.find_by(description:'Santander').id)
City.create(description:'MACARAVITA', state_id: State.find_by(description:'Santander').id)
City.create(description:'MÁLAGA', state_id: State.find_by(description:'Santander').id)
City.create(description:'MATANZA', state_id: State.find_by(description:'Santander').id)
City.create(description:'MOGOTES', state_id: State.find_by(description:'Santander').id)
City.create(description:'MOLAGAVITA', state_id: State.find_by(description:'Santander').id)
City.create(description:'OCAMONTE', state_id: State.find_by(description:'Santander').id)
City.create(description:'OIBA', state_id: State.find_by(description:'Santander').id)
City.create(description:'ONZAGA', state_id: State.find_by(description:'Santander').id)
City.create(description:'PALMAR', state_id: State.find_by(description:'Santander').id)
City.create(description:'PALMAS DEL SOCORRO', state_id: State.find_by(description:'Santander').id)
City.create(description:'PÁRAMO', state_id: State.find_by(description:'Santander').id)
City.create(description:'PIEDECUESTA', state_id: State.find_by(description:'Santander').id)
City.create(description:'PINCHOTE', state_id: State.find_by(description:'Santander').id)
City.create(description:'PUENTE NACIONAL', state_id: State.find_by(description:'Santander').id)
City.create(description:'PUERTO PARRA', state_id: State.find_by(description:'Santander').id)
City.create(description:'PUERTO WILCHES', state_id: State.find_by(description:'Santander').id)
City.create(description:'RIONEGRO', state_id: State.find_by(description:'Santander').id)
City.create(description:'SABANA DE TORRES', state_id: State.find_by(description:'Santander').id)
City.create(description:'SAN ANDRÉS', state_id: State.find_by(description:'Santander').id)
City.create(description:'SAN BENITO', state_id: State.find_by(description:'Santander').id)
City.create(description:'SAN GIL', state_id: State.find_by(description:'Santander').id)
City.create(description:'SAN JOAQUÍN', state_id: State.find_by(description:'Santander').id)
City.create(description:'SAN JOSÉ DE MIRANDA', state_id: State.find_by(description:'Santander').id)
City.create(description:'SAN MIGUEL', state_id: State.find_by(description:'Santander').id)
City.create(description:'SAN VICENTE DE CHUCURÍ', state_id: State.find_by(description:'Santander').id)
City.create(description:'SANTA BÁRBARA', state_id: State.find_by(description:'Santander').id)
City.create(description:'SANTA HELENA DEL OPÓN', state_id: State.find_by(description:'Santander').id)
City.create(description:'SIMACOTA', state_id: State.find_by(description:'Santander').id)
City.create(description:'SOCORRO', state_id: State.find_by(description:'Santander').id)
City.create(description:'SUAITA', state_id: State.find_by(description:'Santander').id)
City.create(description:'SUCRE', state_id: State.find_by(description:'Santander').id)
City.create(description:'SURATÁ', state_id: State.find_by(description:'Santander').id)
City.create(description:'TONA', state_id: State.find_by(description:'Santander').id)
City.create(description:'VALLE DE SAN JOSÉ', state_id: State.find_by(description:'Santander').id)
City.create(description:'VÉLEZ', state_id: State.find_by(description:'Santander').id)
City.create(description:'VETAS', state_id: State.find_by(description:'Santander').id)
City.create(description:'VILLANUEVA', state_id: State.find_by(description:'Santander').id)
City.create(description:'ZAPATOCA', state_id: State.find_by(description:'Santander').id)
City.create(description:'BUENAVISTA', state_id: State.find_by(description:'Sucre').id)
City.create(description:'CAIMITO', state_id: State.find_by(description:'Sucre').id)
City.create(description:'CHALÁN', state_id: State.find_by(description:'Sucre').id)
City.create(description:'COLOSO', state_id: State.find_by(description:'Sucre').id)
City.create(description:'COROZAL', state_id: State.find_by(description:'Sucre').id)
City.create(description:'COVEÑAS', state_id: State.find_by(description:'Sucre').id)
City.create(description:'EL ROBLE', state_id: State.find_by(description:'Sucre').id)
City.create(description:'GALERAS', state_id: State.find_by(description:'Sucre').id)
City.create(description:'GUARANDA', state_id: State.find_by(description:'Sucre').id)
City.create(description:'LA UNIÓN', state_id: State.find_by(description:'Sucre').id)
City.create(description:'LOS PALMITOS', state_id: State.find_by(description:'Sucre').id)
City.create(description:'MAJAGUAL', state_id: State.find_by(description:'Sucre').id)
City.create(description:'MORROA', state_id: State.find_by(description:'Sucre').id)
City.create(description:'OVEJAS', state_id: State.find_by(description:'Sucre').id)
City.create(description:'PALMITO', state_id: State.find_by(description:'Sucre').id)
City.create(description:'SAMPUÉS', state_id: State.find_by(description:'Sucre').id)
City.create(description:'SAN BENITO ABAD', state_id: State.find_by(description:'Sucre').id)
City.create(description:'SAN JUAN DE BETULIA', state_id: State.find_by(description:'Sucre').id)
City.create(description:'SAN LUIS DE SINCÉ', state_id: State.find_by(description:'Sucre').id)
City.create(description:'SAN MARCOS', state_id: State.find_by(description:'Sucre').id)
City.create(description:'SAN ONOFRE', state_id: State.find_by(description:'Sucre').id)
City.create(description:'SAN PEDRO', state_id: State.find_by(description:'Sucre').id)
City.create(description:'SANTIAGO DE TOLÚ', state_id: State.find_by(description:'Sucre').id)
City.create(description:'SINCELEJO', state_id: State.find_by(description:'Sucre').id)
City.create(description:'SUCRE', state_id: State.find_by(description:'Sucre').id)
City.create(description:'TOLÚ VIEJO', state_id: State.find_by(description:'Sucre').id)
City.create(description:'ALPUJARRA', state_id: State.find_by(description:'Tolima').id)
City.create(description:'ALVARADO', state_id: State.find_by(description:'Tolima').id)
City.create(description:'AMBALEMA', state_id: State.find_by(description:'Tolima').id)
City.create(description:'ANZOÁTEGUI', state_id: State.find_by(description:'Tolima').id)
City.create(description:'ARMERO', state_id: State.find_by(description:'Tolima').id)
City.create(description:'ATACO', state_id: State.find_by(description:'Tolima').id)
City.create(description:'CAJAMARCA', state_id: State.find_by(description:'Tolima').id)
City.create(description:'CARMEN DE APICALÁ', state_id: State.find_by(description:'Tolima').id)
City.create(description:'CASABIANCA', state_id: State.find_by(description:'Tolima').id)
City.create(description:'CHAPARRAL', state_id: State.find_by(description:'Tolima').id)
City.create(description:'COELLO', state_id: State.find_by(description:'Tolima').id)
City.create(description:'COYAIMA', state_id: State.find_by(description:'Tolima').id)
City.create(description:'CUNDAY', state_id: State.find_by(description:'Tolima').id)
City.create(description:'DOLORES', state_id: State.find_by(description:'Tolima').id)
City.create(description:'ESPINAL', state_id: State.find_by(description:'Tolima').id)
City.create(description:'FALAN', state_id: State.find_by(description:'Tolima').id)
City.create(description:'FLANDES', state_id: State.find_by(description:'Tolima').id)
City.create(description:'FRESNO', state_id: State.find_by(description:'Tolima').id)
City.create(description:'GUAMO', state_id: State.find_by(description:'Tolima').id)
City.create(description:'HERVEO', state_id: State.find_by(description:'Tolima').id)
City.create(description:'HONDA', state_id: State.find_by(description:'Tolima').id)
City.create(description:'ICONONZO', state_id: State.find_by(description:'Tolima').id)
City.create(description:'LÉRIDA', state_id: State.find_by(description:'Tolima').id)
City.create(description:'LÍBANO', state_id: State.find_by(description:'Tolima').id)
City.create(description:'MARIQUITA', state_id: State.find_by(description:'Tolima').id)
City.create(description:'MURILLO', state_id: State.find_by(description:'Tolima').id)
City.create(description:'NATAGAIMA', state_id: State.find_by(description:'Tolima').id)
City.create(description:'ORTEGA', state_id: State.find_by(description:'Tolima').id)
City.create(description:'PALOCABILDO', state_id: State.find_by(description:'Tolima').id)
City.create(description:'PIEDRAS', state_id: State.find_by(description:'Tolima').id)
City.create(description:'PLANADAS', state_id: State.find_by(description:'Tolima').id)
City.create(description:'PRADO', state_id: State.find_by(description:'Tolima').id)
City.create(description:'PURIFICACIÓN', state_id: State.find_by(description:'Tolima').id)
City.create(description:'RIOBLANCO', state_id: State.find_by(description:'Tolima').id)
City.create(description:'RONCESVALLES', state_id: State.find_by(description:'Tolima').id)
City.create(description:'ROVIRA', state_id: State.find_by(description:'Tolima').id)
City.create(description:'SALDAÑA', state_id: State.find_by(description:'Tolima').id)
City.create(description:'SAN ANTONIO', state_id: State.find_by(description:'Tolima').id)
City.create(description:'SAN LUIS', state_id: State.find_by(description:'Tolima').id)
City.create(description:'SANTA ISABEL', state_id: State.find_by(description:'Tolima').id)
City.create(description:'SUÁREZ', state_id: State.find_by(description:'Tolima').id)
City.create(description:'VALLE DE SAN JUAN', state_id: State.find_by(description:'Tolima').id)
City.create(description:'VENADILLO', state_id: State.find_by(description:'Tolima').id)
City.create(description:'VILLAHERMOSA', state_id: State.find_by(description:'Tolima').id)
City.create(description:'VILLARRICA', state_id: State.find_by(description:'Tolima').id)
City.create(description:'ALCALÁ', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'ANDALUCÍA', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'ANSERMANUEVO', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'ARGELIA', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'BOLÍVAR', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'BUENAVENTURA', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'BUGALAGRANDE', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'CAICEDONIA', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'CALIMA', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'CANDELARIA', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'CARTAGO', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'DAGUA', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'EL ÁGUILA', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'EL CAIRO', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'EL CERRITO', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'EL DOVIO', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'FLORIDA', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'GINEBRA', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'GUACARÍ', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'GUADALAJARA DE BUGA', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'JAMUNDÍ', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'LA CUMBRE', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'LA UNIÓN', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'LA VICTORIA', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'OBANDO', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'PALMIRA', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'PRADERA', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'RESTREPO', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'RIOFRÍO', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'ROLDANILLO', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'SAN PEDRO', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'SEVILLA', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'TORO', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'TRUJILLO', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'TULUÁ', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'ULLOA', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'VERSALLES', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'VIJES', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'YOTOCO', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'YUMBO', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'ZARZAL', state_id: State.find_by(description:'Valle del Cauca').id)
City.create(description:'CARURU', state_id: State.find_by(description:'Vaupés').id)
City.create(description:'MITÚ', state_id: State.find_by(description:'Vaupés').id)
City.create(description:'PACOA', state_id: State.find_by(description:'Vaupés').id)
City.create(description:'PAPUNAUA', state_id: State.find_by(description:'Vaupés').id)
City.create(description:'TARAIRA', state_id: State.find_by(description:'Vaupés').id)
City.create(description:'YAVARATÉ', state_id: State.find_by(description:'Vaupés').id)
City.create(description:'CUMARIBO', state_id: State.find_by(description:'Vichada').id)
City.create(description:'LA PRIMAVERA', state_id: State.find_by(description:'Vichada').id)
City.create(description:'PUERTO CARREÑO', state_id: State.find_by(description:'Vichada').id)
City.create(description:'SANTA ROSALÍA', state_id: State.find_by(description:'Vichada').id)

  end
end
